"""Integration tests for D-1 RequestIdMiddleware wiring on the real owlmlx app.

These tests construct the actual owlmlx FastAPI app via
``owlmlx.runtime.server.create_app(...)`` and exercise the middleware
end-to-end with ``fastapi.testclient.TestClient``. No uvicorn process
is spawned and no model is loaded; ``/healthz`` (and a 404 path) are
sufficient to observe the middleware's lossless inbound/outbound
contract.

The companion file ``tests/test_serving_hardening.py`` (committed in
the C-4 scaffold round) exercises the middleware against a minimal
stub Starlette app. This file exists to prove the middleware is in
fact installed on the real owlmlx app after the D-1 wiring round.
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from owlmlx.runtime.server import create_app
from owlmlx.runtime.serving_hardening import REQUEST_ID_HEADER


def _build_real_owlmlx_app():
    """Build the real owlmlx FastAPI app with no optional ledgers wired.

    Constructed via ``create_app()`` with default kwargs so the
    ``FakeBackend`` is used and no ledger paths are touched. ``/healthz``
    does not require any backend to be loaded; the route reads only
    the runtime kernel's status surface.
    """

    return create_app()


def test_inbound_request_id_propagates_to_outbound_on_healthz() -> None:
    """An inbound x-request-id header is preserved verbatim on the outbound response."""

    app = _build_real_owlmlx_app()
    inbound_id = "caller-supplied-d1-wiring-test-id"
    with TestClient(app) as client:
        response = client.get("/healthz", headers={REQUEST_ID_HEADER: inbound_id})
    assert response.status_code == 200
    assert response.headers[REQUEST_ID_HEADER] == inbound_id


def test_outbound_request_id_autogenerated_when_inbound_absent_on_healthz() -> None:
    """When the request lacks x-request-id, the response carries an autogenerated id."""

    app = _build_real_owlmlx_app()
    with TestClient(app) as client:
        response = client.get("/healthz")
    assert response.status_code == 200
    assert REQUEST_ID_HEADER in response.headers
    out_id = response.headers[REQUEST_ID_HEADER]
    # Per RequestIdMiddleware contract: req_<uuid4hex> (32 hex chars).
    assert out_id.startswith("req_")
    assert len(out_id) == len("req_") + 32


def test_healthz_body_unchanged_with_or_without_inbound_request_id() -> None:
    """Middleware is lossless on the response body — only headers change."""

    app = _build_real_owlmlx_app()
    with TestClient(app) as client:
        response_without = client.get("/healthz")
        response_with = client.get(
            "/healthz", headers={REQUEST_ID_HEADER: "another-caller-id"}
        )
    assert response_without.status_code == 200
    assert response_with.status_code == 200
    assert response_without.json() == response_with.json()


def test_request_id_header_present_on_404_path() -> None:
    """Middleware also writes x-request-id on routes FastAPI did not register."""

    app = _build_real_owlmlx_app()
    with TestClient(app) as client:
        response = client.get("/nonexistent")
    assert response.status_code == 404
    assert REQUEST_ID_HEADER in response.headers
    out_id = response.headers[REQUEST_ID_HEADER]
    assert out_id.startswith("req_")
    assert len(out_id) == len("req_") + 32


def test_inbound_request_id_propagates_on_404_path() -> None:
    """Lossless contract holds even when the route does not exist."""

    app = _build_real_owlmlx_app()
    inbound_id = "caller-supplied-on-404-path"
    with TestClient(app) as client:
        response = client.get("/nonexistent", headers={REQUEST_ID_HEADER: inbound_id})
    assert response.status_code == 404
    assert response.headers[REQUEST_ID_HEADER] == inbound_id
