"""Integration tests for D-5 per-route request_id dedup on the real owlmlx app.

These tests construct the actual owlmlx FastAPI app via
``owlmlx.runtime.server.create_app(...)`` and exercise the compat
routes (``/v1/chat/completions``, ``/v1/messages``, ``/v1/completions``)
end-to-end with ``fastapi.testclient.TestClient``. No uvicorn process
is spawned and no model is loaded.

Background: prior to D-5, each compat route generated its own
``req_<uuid4hex>`` locally — in parallel to the D-1
``RequestIdMiddleware`` that already sets ``request.state.request_id``
(honoring inbound ``x-request-id`` if present). D-5 removes that
per-route generation so the middleware-set id is the single source.

These tests pin the new contract:

- Inbound ``x-request-id`` propagates verbatim into compat response
  body's ``id`` field (chat completions, messages, completions).
- When no inbound id is provided, the autogenerated middleware id
  matches the response body's ``id`` (single source proof).
- Compat error envelope's ``request_id``/``id`` field carries the
  inbound ``x-request-id`` (no longer a freshly generated value).

The companion file ``tests/test_serving_hardening_wired.py`` exercises
the middleware on ``/healthz`` and 404 paths; this file is the compat
route counterpart.
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from owlmlx.runtime.server import create_app
from owlmlx.runtime.serving_hardening import REQUEST_ID_HEADER


def _build_real_owlmlx_app():
    """Build the real owlmlx FastAPI app with no optional ledgers wired."""

    return create_app()


def test_inbound_request_id_propagates_to_chat_completions_response_id() -> None:
    """Inbound x-request-id is the value that lands in compat error body's ``id``.

    POST /v1/chat/completions against an unloaded model triggers the
    ``model_not_loaded`` error path which routes through
    ``_compat_error_response`` — that builder uses ``request_id`` for
    both the ``x-request-id`` header and the body's ``id`` field. After
    D-5, the ``request_id`` value comes from
    ``request.state.request_id`` (i.e. the middleware) rather than a
    fresh local uuid, so an inbound header MUST round-trip verbatim.
    """

    app = _build_real_owlmlx_app()
    inbound_id = "req_test-inbound-123"
    with TestClient(app) as client:
        response = client.post(
            "/v1/chat/completions",
            headers={REQUEST_ID_HEADER: inbound_id},
            json={
                "model": "no-such-model-d5",
                "messages": [{"role": "user", "content": "hello"}],
            },
        )
    assert response.status_code in (404, 503), response.text
    assert response.headers[REQUEST_ID_HEADER] == inbound_id
    body = response.json()
    assert body["id"] == inbound_id
    assert body["object"] == "error"


def test_inbound_request_id_propagates_to_messages_response_id() -> None:
    """Inbound x-request-id propagates into Anthropic ``/v1/messages`` error path.

    The Anthropic error envelope does not place ``request_id`` in the
    body — only the ``x-request-id`` header — but the header value is
    still the source-of-truth id. D-5 ensures that header is the
    middleware-set id (matching the inbound).
    """

    app = _build_real_owlmlx_app()
    inbound_id = "req_test-inbound-msgs-456"
    with TestClient(app) as client:
        response = client.post(
            "/v1/messages",
            headers={REQUEST_ID_HEADER: inbound_id},
            json={
                "model": "no-such-model-d5-anthropic",
                "messages": [{"role": "user", "content": "hello"}],
                "max_tokens": 16,
            },
        )
    assert response.status_code in (404, 503), response.text
    assert response.headers[REQUEST_ID_HEADER] == inbound_id


def test_inbound_request_id_propagates_to_completions_response_id() -> None:
    """Inbound x-request-id is the value that lands in /v1/completions error body's ``id``."""

    app = _build_real_owlmlx_app()
    inbound_id = "req_test-inbound-cmpl-789"
    with TestClient(app) as client:
        response = client.post(
            "/v1/completions",
            headers={REQUEST_ID_HEADER: inbound_id},
            json={
                "model": "no-such-model-d5-cmpl",
                "prompt": "hello",
            },
        )
    assert response.status_code in (404, 503), response.text
    assert response.headers[REQUEST_ID_HEADER] == inbound_id
    body = response.json()
    assert body["id"] == inbound_id
    assert body["object"] == "error"


def test_no_inbound_id_uses_middleware_generated_id_in_compat_response() -> None:
    """No inbound header: response body's ``id`` matches the response's x-request-id header.

    Proves the middleware-generated id is the single source for both
    the outbound header AND the compat body's ``id`` field. Before
    D-5, these would have been two independently generated values.
    """

    app = _build_real_owlmlx_app()
    with TestClient(app) as client:
        response = client.post(
            "/v1/chat/completions",
            json={
                "model": "no-such-model-d5-autogen",
                "messages": [{"role": "user", "content": "hello"}],
            },
        )
    assert response.status_code in (404, 503), response.text
    assert REQUEST_ID_HEADER in response.headers
    header_id = response.headers[REQUEST_ID_HEADER]
    # Per RequestIdMiddleware contract: req_<uuid4hex> (32 hex chars).
    assert header_id.startswith("req_")
    assert len(header_id) == len("req_") + 32
    body = response.json()
    # Body ``id`` is the same middleware-set value as the header.
    assert body["id"] == header_id


def test_compat_error_response_carries_inbound_request_id() -> None:
    """Compat error envelope's ``id`` (= ``request_id``) reflects inbound x-request-id.

    Triggered via POST /v1/completions with an unknown model_id, which
    drives the ``model_not_loaded`` error path. The compat error
    envelope places ``request_id`` in the body's ``id`` field. D-5
    means that value is the middleware-set id, so the inbound header
    must round-trip into the body.
    """

    app = _build_real_owlmlx_app()
    inbound_id = "req_test-error-envelope-d5-abc"
    with TestClient(app) as client:
        response = client.post(
            "/v1/completions",
            headers={REQUEST_ID_HEADER: inbound_id},
            json={
                "model": "no-such-model-d5-error",
                "prompt": "hello",
            },
        )
    assert response.status_code in (404, 503), response.text
    body = response.json()
    assert body["id"] == inbound_id
    assert body["object"] == "error"
    assert response.headers[REQUEST_ID_HEADER] == inbound_id


def test_openai_models_route_uses_middleware_request_id() -> None:
    """GET /v1/openai/models response x-request-id matches inbound (D-5 dedup).

    Before D-5, this route also generated its own request_id. After
    D-5 it pulls from ``request.state.request_id``, so an inbound
    ``x-request-id`` round-trips verbatim on a successful GET.
    """

    app = _build_real_owlmlx_app()
    inbound_id = "req_test-openai-models-d5-xyz"
    with TestClient(app) as client:
        response = client.get(
            "/v1/openai/models",
            headers={REQUEST_ID_HEADER: inbound_id},
        )
    assert response.status_code == 200
    assert response.headers[REQUEST_ID_HEADER] == inbound_id
    body = response.json()
    assert body["object"] == "list"
