"""owlmlx serving hardening scaffold.

Defines the middleware, async helpers, and response shapes for six
serving-surface hardenings that improve credibility independent of any
batching or scheduler change:

1. Request-id propagation middleware
2. Per-request timeout + client-disconnect detection
3. Graceful shutdown that drains the GenerationGate
4. Unified structured error envelope
5. Prometheus-format metrics snapshot exporter (stdlib only)
6. Idempotent ``/v1/load`` outcome envelope

Scaffold-grade. ``runtime/server.py`` is NOT modified in this round to
install any of these. Wiring is a follow-up round whose responsibility
is to apply ``app.add_middleware(RequestIdMiddleware)``, attach the
graceful shutdown to ``app.router.on_shutdown``, etc., one item at a
time with operator review per hardening.

Ownership boundary:

- this module owns *primitives*: middleware classes, async helpers,
  immutable result/policy dataclasses, and a stdlib-only Prometheus text
  renderer
- ``runtime/server.py`` (lines 1-2343) remains read-only in this round;
  no FastAPI app is constructed here, no route is registered here, no
  ``app.add_middleware`` / ``app.add_exception_handler`` /
  ``app.router.on_shutdown`` call is made here
- ``owlmlx/serving.py`` ``GenerationGate`` (lines 104-979) is NOT
  imported here. The graceful shutdown receives a *callable* returning
  the same dict shape ``GenerationGate.status`` exposes, so the operator
  decides at wiring time which gate the drain observes
- ``owlmlx/runtime/mlx_native_backend.py`` ``_TicketedAdmission``
  ``snapshot()`` is also referenced only via dict shape; no import

Per ``docs/source-of-truth/native-mlx-backend-capability-matrix.md`` §7
the seven-line architectural assessment records **Line 4 — Serving
surface (`partial`)** as the lane this scaffold begins to close. The
matrix itself is about MLX backend capability entry points, not HTTP
serving primitives, so this scaffold does NOT promote any matrix row.
Serving-surface ownership is governed by
``docs/source-of-truth/single-host-orchestration-architecture.md`` and
the architecture doc that ships alongside this scaffold.

No new dependencies. The Prometheus text-exposition format is rendered
manually with ``io.StringIO`` so that neither ``prometheus_client`` nor
``psutil`` is added. Starlette pieces are imported because FastAPI
already depends on Starlette (FastAPI re-exports it); we use the
``starlette`` import path directly to make the boundary explicit.
"""

from __future__ import annotations

import asyncio
import io
import json
import time
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable
from dataclasses import dataclass
from typing import Any

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


# ---------------------------------------------------------------------------
# 1. Request-id propagation
# ---------------------------------------------------------------------------


REQUEST_ID_HEADER = "x-request-id"
"""Canonical inbound/outbound header name for request-id propagation.

Lowercased per the HTTP/2 spec normalization that Starlette and FastAPI
apply when parsing request headers; outbound responses are written with
the same lowercase form for symmetry.
"""


@dataclass(frozen=True, slots=True)
class RequestIdContext:
    """Immutable record of how a request id was determined.

    ``inbound = True`` means the value came from the request header
    unchanged. ``inbound = False`` means the middleware generated a new
    id (the caller did not send one). The middleware NEVER overrides an
    inbound id; that is the lossless guarantee the wiring round can rely
    on when threading the id through structured logs.
    """

    request_id: str
    inbound: bool

    def to_dict(self) -> dict[str, Any]:
        return {"request_id": self.request_id, "inbound": self.inbound}


def _generate_request_id() -> str:
    """Return a fresh request id of shape ``req_<uuid4hex>``.

    The ``req_`` prefix mirrors the convention used elsewhere in the
    codebase for ticket-style identifiers and lets log scrapers tell at
    a glance whether the id was generated by owlmlx vs supplied by an
    upstream caller. UUID-4 hex (32 chars) is collision-resistant
    without coordinating state.
    """

    return f"req_{uuid.uuid4().hex}"


def derive_request_id_context(inbound_header_value: str | None) -> RequestIdContext:
    """Pure helper: derive the ``RequestIdContext`` for a header value.

    Extracted from ``RequestIdMiddleware`` so unit tests do not need a
    Starlette ``Request`` instance to verify the inbound/outbound rules.

    - non-empty trimmed inbound value -> ``inbound = True`` and the
      value is preserved verbatim
    - missing or empty value -> a fresh ``req_<uuid4hex>`` id is
      generated and ``inbound = False``
    """

    if inbound_header_value is None:
        return RequestIdContext(request_id=_generate_request_id(), inbound=False)
    trimmed = inbound_header_value.strip()
    if not trimmed:
        return RequestIdContext(request_id=_generate_request_id(), inbound=False)
    return RequestIdContext(request_id=trimmed, inbound=True)


class RequestIdMiddleware(BaseHTTPMiddleware):
    """Inbound/outbound ``x-request-id`` propagation.

    Inbound: read ``x-request-id`` from request headers; if absent or
    empty, generate ``req_<uuid4hex>`` via :func:`_generate_request_id`.
    Attach the resulting :class:`RequestIdContext` to
    ``request.state.request_id_context`` and the bare id to
    ``request.state.request_id`` (the bare id is the field handlers and
    structured loggers want most of the time; the context object is
    available for callers that need to know whether the id was
    inbound).

    Outbound: ensure the response carries ``x-request-id``. If the
    downstream handler already wrote one, do not overwrite it; only set
    when missing.

    Lossless contract: an inbound id is NEVER replaced. The wiring round
    can therefore rely on this middleware as the single point of truth
    for the request-id field in structured logs, error envelopes, and
    metrics labels.
    """

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        inbound_value = request.headers.get(REQUEST_ID_HEADER)
        context = derive_request_id_context(inbound_value)
        request.state.request_id_context = context
        request.state.request_id = context.request_id
        response = await call_next(request)
        # Lossless: never overwrite a header the handler already set.
        if REQUEST_ID_HEADER not in response.headers:
            response.headers[REQUEST_ID_HEADER] = context.request_id
        return response


# ---------------------------------------------------------------------------
# 2. Per-request timeout + client-disconnect detection
# ---------------------------------------------------------------------------


class RequestDisconnectedError(Exception):
    """Raised when ``poll_disconnect`` observes the client has gone away.

    The wiring round catches this in handler scope and converts it to
    the unified error envelope (see :class:`ErrorEnvelopeBuilder`) with
    ``error_code = "client_disconnected"`` and HTTP 499-equivalent. This
    scaffold does NOT decide the HTTP code; the wiring round decides
    that policy.
    """


@dataclass(frozen=True, slots=True)
class RequestTimeoutPolicy:
    """Per-request timeout policy.

    - ``default_timeout_s``: ceiling for non-streaming generation
      requests. Sized larger than typical decode latency; the wiring
      round may override per-route at install time.
    - ``streaming_timeout_s``: ceiling for streaming generation
      requests, sized larger because streaming responses can legitimately
      run for minutes on large weights.
    - ``disconnect_check_interval_s``: cadence for
      ``RequestTimeoutHelper.poll_disconnect`` to await
      ``Request.is_disconnected()``. Too short and the polling cost
      shows up in CPU profiles; too long and disconnect detection lags.
    """

    default_timeout_s: float = 60.0
    streaming_timeout_s: float = 600.0
    disconnect_check_interval_s: float = 0.5


class RequestTimeoutHelper:
    """Async helpers for timeout-bounded handlers and disconnect polling.

    This is async-native at the timeout boundary: ``await_with_timeout``
    is implemented via :func:`asyncio.wait_for`, NOT via threading or
    process spawn. The scaffold deliberately does not block on a thread
    waiting for the awaitable, because the FastAPI app is async and
    blocking the event loop for a timeout is the wrong shape.
    """

    def __init__(self, *, policy: RequestTimeoutPolicy | None = None) -> None:
        self._policy = policy or RequestTimeoutPolicy()

    @property
    def policy(self) -> RequestTimeoutPolicy:
        return self._policy

    async def await_with_timeout(
        self,
        awaitable: Awaitable[Any],
        *,
        timeout_s: float | None = None,
    ) -> Any:
        """Await ``awaitable`` with a per-call timeout.

        ``timeout_s`` overrides the policy's ``default_timeout_s`` when
        supplied. When ``timeout_s`` resolves to ``None`` (e.g. the
        wiring round disables the ceiling for a specific route), the
        awaitable runs unbounded — i.e. the helper degrades to a
        no-timeout wrapper rather than refusing the call.
        """

        effective_timeout = timeout_s if timeout_s is not None else self._policy.default_timeout_s
        if effective_timeout is None:
            return await awaitable
        return await asyncio.wait_for(awaitable, timeout=effective_timeout)

    async def poll_disconnect(
        self,
        request: Request,
        *,
        interval_s: float | None = None,
    ) -> AsyncIterator[None]:
        """Async generator that yields periodically until the client disconnects.

        Usage shape (deferred to the wiring round):

        .. code-block:: python

            async def handler(request: Request) -> Response:
                helper = RequestTimeoutHelper()
                gen_task = asyncio.create_task(_run_generation(request))
                async for _ in helper.poll_disconnect(request):
                    if gen_task.done():
                        break
                    # client still there

        Raises :class:`RequestDisconnectedError` once
        ``await request.is_disconnected()`` returns ``True``. The
        wiring round is responsible for cancelling the generation task
        upon catching this exception; the scaffold does not couple to
        any specific cancellation strategy.
        """

        cadence = (
            interval_s
            if interval_s is not None
            else self._policy.disconnect_check_interval_s
        )
        while True:
            disconnected = await request.is_disconnected()
            if disconnected:
                raise RequestDisconnectedError(
                    "client closed the connection before the response completed"
                )
            yield None
            await asyncio.sleep(cadence)


# ---------------------------------------------------------------------------
# 3. Graceful shutdown that drains the GenerationGate
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class GracefulShutdownConfig:
    """Configuration for the shutdown drain.

    - ``gate_idle_timeout_s``: maximum total time the drain waits for
      the gate to become idle before giving up and reporting timeout.
      Sized to a single-generation ceiling; the wiring round may raise
      it for fleets that deliberately allow long completions to
      finish.
    - ``unload_models_on_shutdown``: when ``True``, after the drain
      completes (whether by idle observation or timeout) the wiring
      round invokes the optional unload callable to release in-process
      model handles and trigger ``mx.clear_cache`` if the runtime
      extra is present.
    - ``poll_interval_s``: cadence at which ``drain_gate`` re-reads
      the gate status. Short enough that a freshly-idle gate is
      observed quickly; long enough that the polling loop is not a
      hot loop.
    """

    gate_idle_timeout_s: float = 30.0
    unload_models_on_shutdown: bool = True
    poll_interval_s: float = 0.05


class GracefulShutdown:
    """Drain the gate, then optionally unload models.

    Receives the gate's status surface as a *callable*, not as a direct
    reference to ``GenerationGate``. This keeps the scaffold decoupled
    from ``owlmlx/serving.py``: the operator passes
    ``lambda: gate.status`` (or any equivalent) at wiring time. The
    scaffold only assumes the dict has an ``is_active`` field that mirrors
    ``GenerationGate.is_active``'s boolean shape, plus opaque other
    fields it forwards verbatim into the shutdown report.

    The drain is observation-only. It does NOT call any gate method,
    does NOT cancel any in-flight generation, does NOT mutate gate
    state. If the operator needs forced cancellation, that is a separate
    primitive whose wiring is also deferred.
    """

    def __init__(self, *, config: GracefulShutdownConfig | None = None) -> None:
        self._config = config or GracefulShutdownConfig()

    @property
    def config(self) -> GracefulShutdownConfig:
        return self._config

    async def drain_gate(
        self,
        *,
        gate_status_callable: Callable[[], dict[str, Any]],
    ) -> dict[str, Any]:
        """Poll ``gate_status_callable()`` until idle or timeout.

        Returns a dict::

            {
                "drained": bool,            # True iff observed idle in time
                "elapsed_s": float,         # wall time spent draining
                "polls": int,               # number of status reads
                "final_status": dict,       # last observed status payload
                "timeout_s": float,         # config ceiling, for audit
            }

        The status payload shape is unchanged from what the callable
        returns; the scaffold only reads ``is_active`` from it. ``polls``
        is reported so the wiring round's structured shutdown log can
        distinguish "drained on first poll" (clean idle) from
        "drained after a long tail" (legitimate long-running
        generation).
        """

        deadline = time.monotonic() + self._config.gate_idle_timeout_s
        started_at = time.monotonic()
        polls = 0
        last_status: dict[str, Any] = {}
        drained = False
        while True:
            polls += 1
            last_status = gate_status_callable()
            if not last_status.get("is_active", False):
                drained = True
                break
            if time.monotonic() >= deadline:
                drained = False
                break
            await asyncio.sleep(self._config.poll_interval_s)
        elapsed = time.monotonic() - started_at
        return {
            "drained": drained,
            "elapsed_s": round(elapsed, 4),
            "polls": polls,
            "final_status": last_status,
            "timeout_s": self._config.gate_idle_timeout_s,
        }

    async def on_shutdown(
        self,
        *,
        gate_status_callable: Callable[[], dict[str, Any]],
        unload_models_callable: Callable[[], Awaitable[dict[str, Any]] | dict[str, Any]]
        | None = None,
    ) -> dict[str, Any]:
        """Orchestrate drain then optional unload.

        ``unload_models_callable`` may be sync or async; both shapes
        are accepted because owlmlx's existing unload paths are
        synchronous (``MlxNativeBackend.unload`` returns a dataclass)
        but a future round may want async unload to overlap with cache
        clear. The scaffold accepts both; if the callable returns a
        dict directly it is treated as the unload report.

        The returned report is a dict suitable for embedding in the
        runtime's structured shutdown log. It is NOT a Pydantic model
        because lifespan handlers do not return Pydantic anyway.
        """

        drain_report = await self.drain_gate(gate_status_callable=gate_status_callable)
        unload_report: dict[str, Any] | None = None
        if self._config.unload_models_on_shutdown and unload_models_callable is not None:
            outcome = unload_models_callable()
            if asyncio.iscoroutine(outcome) or hasattr(outcome, "__await__"):
                unload_report = await outcome  # type: ignore[assignment]
            else:
                unload_report = outcome  # type: ignore[assignment]
        return {
            "drain": drain_report,
            "unload": unload_report,
            "config": {
                "gate_idle_timeout_s": self._config.gate_idle_timeout_s,
                "unload_models_on_shutdown": self._config.unload_models_on_shutdown,
                "poll_interval_s": self._config.poll_interval_s,
            },
        }


# ---------------------------------------------------------------------------
# 4. Unified structured error envelope
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class UnifiedErrorEnvelope:
    """Outbound error response shape for the native namespace.

    Mirrors the OpenAI error-object shape closely enough that operator
    tooling can ingest it without translation, while adding the
    ``request_id`` field the wiring round populates from
    ``request.state.request_id``.

    ``http_status`` is carried alongside the body so that the wiring
    round's exception handler can return ``Response(content=...,
    status_code=envelope.http_status)`` without recomputing the code
    at the response site. This is the surface that closes the
    ``ok=False but HTTP 200`` mismatch the seven-line assessment
    flagged on Line 4.
    """

    id: str
    error_code: str
    message: str
    request_id: str | None
    http_status: int
    object: str = "error"

    def to_response_body(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "object": self.object,
            "error_code": self.error_code,
            "message": self.message,
            "request_id": self.request_id,
            "http_status": self.http_status,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_response_body(), separators=(",", ":"))


_RUNTIME_ERROR_CODE_TO_HTTP_STATUS: dict[str, int] = {
    "invalid_request": 400,
    "model_not_loaded": 409,
    "model_already_loaded": 409,
    "backend_error": 502,
    "memory_pressure": 503,
    "request_timeout": 504,
    "client_disconnected": 499,
}
"""Static, scaffold-grade mapping from runtime ``error_code`` strings to
HTTP status. The wiring round may extend or override this mapping at
install time; the scaffold only commits to defaults that match the
``runtime/types.py`` ``RuntimeErrorCode`` enum members observable in
``owlmlx`` today.
"""


_UNEXPECTED_ERROR_HTTP_STATUS = 500
"""HTTP status used for ``from_unexpected``. 500 because anything
that bypassed the runtime's typed error path is genuinely an internal
error from the caller's perspective.
"""


class ErrorEnvelopeBuilder:
    """Construct :class:`UnifiedErrorEnvelope` instances safely.

    The ``from_unexpected`` helper deliberately strips the raw
    exception's class name and message from any field that ships in
    the response body. The wiring round logs the underlying exception
    via the structured logger; the response only carries an opaque
    ``"unexpected_error"`` token. This is the no-leak contract the
    serving-surface architecture doc records.
    """

    def __init__(self, *, namespace: str = "owlmlx_native") -> None:
        self._namespace = namespace
        self._counter = 0

    def _next_envelope_id(self) -> str:
        self._counter += 1
        # Random suffix avoids collisions across worker restarts even
        # though there is currently only one worker per process.
        return f"err_{self._namespace}_{uuid.uuid4().hex[:16]}"

    def from_runtime_error_code(
        self,
        *,
        error_code: str,
        message: str,
        request_id: str | None,
        http_status: int | None = None,
    ) -> UnifiedErrorEnvelope:
        """Build an envelope from a typed runtime error.

        ``http_status`` is resolved from
        ``_RUNTIME_ERROR_CODE_TO_HTTP_STATUS`` when not supplied. An
        unknown ``error_code`` defaults to 500; the wiring round can
        narrow this when a domain-specific status fits better.
        """

        resolved_status = (
            http_status
            if http_status is not None
            else _RUNTIME_ERROR_CODE_TO_HTTP_STATUS.get(
                error_code, _UNEXPECTED_ERROR_HTTP_STATUS
            )
        )
        return UnifiedErrorEnvelope(
            id=self._next_envelope_id(),
            error_code=error_code,
            message=message,
            request_id=request_id,
            http_status=resolved_status,
        )

    def from_unexpected(
        self,
        exc: BaseException,
        *,
        request_id: str | None,
    ) -> UnifiedErrorEnvelope:
        """Build an envelope from an untyped exception WITHOUT leaking it.

        ``exc`` is accepted only so the wiring round can pass through
        whatever the framework caught; this method does NOT include the
        exception's class name, message, or traceback in the envelope.
        The wiring round is responsible for logging the exception
        itself elsewhere. The returned envelope's ``message`` is the
        constant ``"unexpected internal error"`` so probes cannot infer
        the exception class from response surface alone.
        """

        # Touch ``exc`` only to silence linters; we deliberately do not
        # read its attributes for the response body.
        _ = type(exc)
        return UnifiedErrorEnvelope(
            id=self._next_envelope_id(),
            error_code="unexpected_error",
            message="unexpected internal error",
            request_id=request_id,
            http_status=_UNEXPECTED_ERROR_HTTP_STATUS,
        )


# ---------------------------------------------------------------------------
# 5. Prometheus-format metrics snapshot exporter (stdlib only)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class _PromMetric:
    """Internal helper for one Prometheus line group.

    Carries the metric name, kind (``counter`` vs ``gauge``), help
    text, and the numeric value. Used only inside
    :class:`MetricsSnapshotExporter`; not part of the public surface.
    """

    name: str
    kind: str
    help_text: str
    value: float


def _format_prom_value(value: Any) -> str:
    """Render a Python numeric/bool into Prometheus-text-format value.

    Booleans become ``1`` / ``0``. Floats and ints render via ``repr``
    with normalization so that the rendered text is stable across
    platforms (no platform-dependent float exponent shifting).
    """

    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value:  # NaN
            return "NaN"
        if value == float("inf"):
            return "+Inf"
        if value == float("-inf"):
            return "-Inf"
        # Avoid scientific notation flapping the diff for small floats.
        text = repr(value)
        return text
    return str(value)


class MetricsSnapshotExporter:
    """Render a Prometheus text-exposition snapshot from owlmlx state.

    Reads two read-only inputs:

    - ``gate_status``: a dict shaped like ``GenerationGate.status``
      (waiters, total_served, total_queued, longest_wait_s,
      longest_exec_s, generation_gate)
    - ``native_admission_snapshot``: optional dict shaped like
      ``MlxNativeBackend.status().detail.admission`` (next_ticket,
      serving, in_critical_section, max_observed_concurrency)

    The exporter does NOT pull these from any module; the wiring round
    is responsible for plumbing them in at the ``/metrics`` route.
    Counter metrics carry ``_total`` suffix per Prometheus convention;
    gauges do not.

    Stdlib-only: rendering uses ``io.StringIO``. ``prometheus_client``
    is intentionally not a dependency.
    """

    def __init__(self, *, namespace: str = "owlmlx_native") -> None:
        self._namespace = namespace

    def _name(self, suffix: str) -> str:
        return f"{self._namespace}_{suffix}"

    def render_prometheus_text(
        self,
        *,
        gate_status: dict[str, Any],
        native_admission_snapshot: dict[str, Any] | None,
    ) -> str:
        """Render the Prometheus text-exposition format snapshot.

        Output shape (one ``# HELP`` and ``# TYPE`` line per metric,
        followed by the value line). Metrics omitted when the source
        dict is missing the field — the exporter does NOT fabricate
        zeros for missing inputs because that would smear the
        boundary between "no data" and "actually zero".
        """

        metrics: list[_PromMetric] = []

        # Gauge: current waiter count
        if "waiters" in gate_status:
            metrics.append(
                _PromMetric(
                    name=self._name("waiters"),
                    kind="gauge",
                    help_text="Number of waiters currently blocked on the GenerationGate.",
                    value=gate_status["waiters"],
                )
            )

        # Counter: total requests served by the gate (cumulative)
        if "total_served" in gate_status:
            metrics.append(
                _PromMetric(
                    name=self._name("total_served_total"),
                    kind="counter",
                    help_text="Cumulative count of generations the gate has admitted to completion.",
                    value=gate_status["total_served"],
                )
            )

        # Counter: total requests queued by the gate
        if "total_queued" in gate_status:
            metrics.append(
                _PromMetric(
                    name=self._name("total_queued_total"),
                    kind="counter",
                    help_text="Cumulative count of generations that had to queue (were not immediately admitted).",
                    value=gate_status["total_queued"],
                )
            )

        # Gauge: longest wait observed (seconds)
        if "longest_wait_s" in gate_status:
            metrics.append(
                _PromMetric(
                    name=self._name("longest_wait_seconds"),
                    kind="gauge",
                    help_text="Longest wait time (seconds) observed since process start.",
                    value=gate_status["longest_wait_s"],
                )
            )

        # Gauge: longest exec observed (seconds)
        if "longest_exec_s" in gate_status:
            metrics.append(
                _PromMetric(
                    name=self._name("longest_exec_seconds"),
                    kind="gauge",
                    help_text="Longest in-gate execution time (seconds) observed since process start.",
                    value=gate_status["longest_exec_s"],
                )
            )

        if native_admission_snapshot is not None:
            if "max_observed_concurrency" in native_admission_snapshot:
                metrics.append(
                    _PromMetric(
                        name=self._name("native_max_observed_concurrency"),
                        kind="gauge",
                        help_text=(
                            "High-water mark of concurrent in-critical-section "
                            "admissions on the native MLX backend."
                        ),
                        value=native_admission_snapshot["max_observed_concurrency"],
                    )
                )
            if "in_critical_section" in native_admission_snapshot:
                metrics.append(
                    _PromMetric(
                        name=self._name("native_in_critical_section"),
                        kind="gauge",
                        help_text=(
                            "Number of admissions currently inside the native "
                            "MLX backend critical section."
                        ),
                        value=native_admission_snapshot["in_critical_section"],
                    )
                )
            if "serving" in native_admission_snapshot:
                metrics.append(
                    _PromMetric(
                        name=self._name("native_serving_ticket"),
                        kind="gauge",
                        help_text=(
                            "Monotonic ticket value the native MLX admission "
                            "is currently serving."
                        ),
                        value=native_admission_snapshot["serving"],
                    )
                )

        buf = io.StringIO()
        for metric in metrics:
            buf.write(f"# HELP {metric.name} {metric.help_text}\n")
            buf.write(f"# TYPE {metric.name} {metric.kind}\n")
            buf.write(f"{metric.name} {_format_prom_value(metric.value)}\n")
        return buf.getvalue()


# ---------------------------------------------------------------------------
# 6. Idempotent ``/v1/load`` outcome envelope
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class IdempotentLoadOutcome:
    """Outcome of an idempotent ``/v1/load`` interpretation step.

    ``already_loaded = True`` means the call's effect was a no-op
    because the model was resident before the call arrived. The wiring
    round translates this to HTTP 200 with a ``detail`` body, NOT to
    HTTP 409.

    ``ok`` is preserved as a separate field rather than collapsed into
    ``already_loaded`` because the typed runtime contract elsewhere
    in owlmlx exposes both. A genuine load failure resolves to
    ``ok = False, already_loaded = False``.
    """

    model_id: str
    already_loaded: bool
    memory_gb: float
    ok: bool = True

    def to_response_body(self) -> dict[str, Any]:
        return {
            "model_id": self.model_id,
            "already_loaded": self.already_loaded,
            "memory_gb": self.memory_gb,
            "ok": self.ok,
        }


class IdempotentLoadHelper:
    """Interpret a backend ``LoadResult``-shaped dict idempotently.

    The native and subprocess backends already return a ``LoadResult``
    dataclass with fields ``ok``, ``error_code``, ``model_id``,
    ``memory_gb``, ``detail``. Today the runtime returns HTTP 409 (or
    similar) when ``error_code == "model_already_loaded"`` even though
    the *caller's intent* — "the model should be resident" — is
    satisfied. This helper rewrites that one specific case into a
    success-with-detail envelope.

    All other failures (``backend_error``, ``invalid_request``, etc.)
    pass through unchanged via ``ok = False``. The wiring round
    converts those into the standard error envelope.
    """

    def interpret_backend_result(
        self,
        *,
        backend_result_dict: dict[str, Any],
    ) -> IdempotentLoadOutcome:
        ok = bool(backend_result_dict.get("ok", False))
        error_code = backend_result_dict.get("error_code")
        model_id = str(backend_result_dict.get("model_id", ""))
        memory_gb = float(backend_result_dict.get("memory_gb", 0.0) or 0.0)
        if not ok and error_code == "model_already_loaded":
            return IdempotentLoadOutcome(
                model_id=model_id,
                already_loaded=True,
                memory_gb=memory_gb,
                ok=True,
            )
        return IdempotentLoadOutcome(
            model_id=model_id,
            already_loaded=False,
            memory_gb=memory_gb,
            ok=ok,
        )


__all__ = [
    "REQUEST_ID_HEADER",
    "RequestIdContext",
    "RequestIdMiddleware",
    "RequestDisconnectedError",
    "RequestTimeoutPolicy",
    "RequestTimeoutHelper",
    "GracefulShutdownConfig",
    "GracefulShutdown",
    "UnifiedErrorEnvelope",
    "ErrorEnvelopeBuilder",
    "MetricsSnapshotExporter",
    "IdempotentLoadOutcome",
    "IdempotentLoadHelper",
    "derive_request_id_context",
]
